/**
 * TS sim-quote verification, pinned against the Rust attestation crate
 * (§2 step 1: Gate 0 fails → C sends NOTHING). The hex vectors below were
 * generated by crates/attestation (`bind_report_data` + `SimAttester`) for
 * nonce = "pramaana-ts-vector-nonce", value = "pramaana-ts-vector-value".
 * If this test reddens, the two languages disagree on the binding bytes and
 * Gate 0 / Gate b would fail silently across the seam — fix the drift,
 * never re-pin casually.
 */

import { hexToBytes } from "@noble/hashes/utils";
import { describe, expect, it } from "vitest";
import {
  AttestationError,
  bindReportData,
  quotedReportData,
  verifyReportDataBinding,
  verifySimQuote,
} from "../src/attestation.js";

const NONCE = new TextEncoder().encode("pramaana-ts-vector-nonce");
const VALUE = new TextEncoder().encode("pramaana-ts-vector-value");

// From the Rust side (see header).
const RUST_REPORT_DATA =
  "0e8628c4c5acb1ec59140d0762d5820ae3994902b8bc3c1131ec3f0f53f07aba" +
  "5f5a425a24ff36c6ea9958c0af1baaea6276449c8f6395edd3d298652c3411f4";
const RUST_QUOTE =
  "5052414d53494d31" + // "PRAMSIM1"
  "5a".repeat(48) + // sim measurement
  "5ee47ce802e372cdab60e02ba5a655b8a637c277927d5e6f3a65cc503104644d" +
  "00".repeat(32); // sha256(report_data) ‖ 0^32

describe("cross-language attestation vector", () => {
  it("bindReportData matches the Rust bytes", () => {
    expect(bindReportData(NONCE, VALUE)).toEqual(hexToBytes(RUST_REPORT_DATA));
  });

  it("a Rust-generated sim quote verifies and binds", () => {
    const verified = verifySimQuote(hexToBytes(RUST_QUOTE));
    verifyReportDataBinding(verified, NONCE, VALUE); // throws on mismatch
    expect(verified.storedReportData).toEqual(
      quotedReportData(hexToBytes(RUST_REPORT_DATA)),
    );
  });
});

describe("Gate 0 appraisal rejections", () => {
  const goodQuote = () => hexToBytes(RUST_QUOTE);

  it("rejects a truncated quote", () => {
    expect(() => verifySimQuote(goodQuote().subarray(0, 100))).toThrow(AttestationError);
  });

  it("rejects bad magic", () => {
    const q = goodQuote();
    q[0] ^= 0xff;
    expect(() => verifySimQuote(q)).toThrow(/magic/);
  });

  it("rejects a measurement outside the appraisal allowlist", () => {
    const q = goodQuote();
    q[10] ^= 0x01; // inside the measurement region
    expect(() => verifySimQuote(q)).toThrow(/allowlist/);
  });

  it("rejects a quote bound to different (nonce, value)", () => {
    const verified = verifySimQuote(goodQuote());
    expect(() =>
      verifyReportDataBinding(verified, NONCE, new TextEncoder().encode("other-value")),
    ).toThrow(/bind/);
  });

  it("rejects a tampered report_data field", () => {
    const q = goodQuote();
    q[60] ^= 0x01; // inside stored_report_data
    const verified = verifySimQuote(q);
    expect(() => verifyReportDataBinding(verified, NONCE, VALUE)).toThrow(/bind/);
  });
});
